// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4h1-3yJCGltgJ5gVvqOvctA7BaUyL6Ls',
    appId: '1:1044088621311:web:e27811ff87fc50dafea4ca',
    messagingSenderId: '1044088621311',
    projectId: 'budget-tracker-2cfd4',
    authDomain: 'budget-tracker-2cfd4.firebaseapp.com',
    storageBucket: 'budget-tracker-2cfd4.firebasestorage.app',
    measurementId: 'G-R5SQF7V9HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaIk441Qi3EXVGIGKCsiWo4O2kIAo3DTA',
    appId: '1:1044088621311:android:4b97e1ce6a818e0dfea4ca',
    messagingSenderId: '1044088621311',
    projectId: 'budget-tracker-2cfd4',
    storageBucket: 'budget-tracker-2cfd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABvNd5QsTvZoVk3aDKlkJfZ_MCzT_pz7M',
    appId: '1:1044088621311:ios:5ec436475c6ed5e0fea4ca',
    messagingSenderId: '1044088621311',
    projectId: 'budget-tracker-2cfd4',
    storageBucket: 'budget-tracker-2cfd4.firebasestorage.app',
    iosBundleId: 'com.example.budgettracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABvNd5QsTvZoVk3aDKlkJfZ_MCzT_pz7M',
    appId: '1:1044088621311:ios:5ec436475c6ed5e0fea4ca',
    messagingSenderId: '1044088621311',
    projectId: 'budget-tracker-2cfd4',
    storageBucket: 'budget-tracker-2cfd4.firebasestorage.app',
    iosBundleId: 'com.example.budgettracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4h1-3yJCGltgJ5gVvqOvctA7BaUyL6Ls',
    appId: '1:1044088621311:web:cc5bdc66c283c561fea4ca',
    messagingSenderId: '1044088621311',
    projectId: 'budget-tracker-2cfd4',
    authDomain: 'budget-tracker-2cfd4.firebaseapp.com',
    storageBucket: 'budget-tracker-2cfd4.firebasestorage.app',
    measurementId: 'G-XN0EQSVXF3',
  );
}
