// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrpWE88FMeHT5lznOG4RtlJf4-4cF5YGM',
    appId: '1:1044088621311:web:6dc7b92c9f4b441bfea4ca',
    messagingSenderId: '1044088621311',
    projectId: 'budget-tracker-2cfd4',
    authDomain: 'budget-tracker-2cfd4.firebaseapp.com',
    storageBucket: 'budget-tracker-2cfd4.firebasestorage.app',
    measurementId: 'G-BJCXFVP4ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaIk441Qi3EXVGIGKCsiWo4O2kIAo3DTA',
    appId: '1:1044088621311:android:b53bb0b294fd97ebfea4ca',
    messagingSenderId: '1044088621311',
    projectId: 'budget-tracker-2cfd4',
    storageBucket: 'budget-tracker-2cfd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABvNd5QsTvZoVk3aDKlkJfZ_MCzT_pz7M',
    appId: '1:1044088621311:ios:990675c054c83762fea4ca',
    messagingSenderId: '1044088621311',
    projectId: 'budget-tracker-2cfd4',
    storageBucket: 'budget-tracker-2cfd4.firebasestorage.app',
    iosBundleId: 'com.budgetTracker.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABvNd5QsTvZoVk3aDKlkJfZ_MCzT_pz7M',
    appId: '1:1044088621311:ios:990675c054c83762fea4ca',
    messagingSenderId: '1044088621311',
    projectId: 'budget-tracker-2cfd4',
    storageBucket: 'budget-tracker-2cfd4.firebasestorage.app',
    iosBundleId: 'com.budgetTracker.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrpWE88FMeHT5lznOG4RtlJf4-4cF5YGM',
    appId: '1:1044088621311:web:da217b3bcc304bf9fea4ca',
    messagingSenderId: '1044088621311',
    projectId: 'budget-tracker-2cfd4',
    authDomain: 'budget-tracker-2cfd4.firebaseapp.com',
    storageBucket: 'budget-tracker-2cfd4.firebasestorage.app',
    measurementId: 'G-42TCBZ1KTH',
  );

}